[versions]
okhttp = "4.12.0"
opentelemetry = "1.57.0"

[libraries]
com-android-tools-build-gradle = { group = "com.android.tools.build", name = "gradle", version = "8.11.0" }
com-azure-azure-core = { group = "com.azure", name = "azure-core", version = "1.57.0" }
com-github-ben-manes-gradle-versions-plugin = { group = "com.github.ben-manes", name = "gradle-versions-plugin", version = "0.52.0" }
com-google-code-gson-gson = { group = "com.google.code.gson", name = "gson", version = "2.13.2" }
com-gradle-gradle-enterprise-gradle-plugin = { group = "com.gradle", name = "gradle-enterprise-gradle-plugin", version = "3.19.2" }
com-squareup-okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
com-squareup-okhttp3-mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp" }
com-squareup-okhttp3-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
io-github-std-uritemplate-std-uritemplate = { group = "io.github.std-uritemplate", name = "std-uritemplate", version = "2.0.0" }
io-opentelemetry-opentelemetry-api = { group = "io.opentelemetry", name = "opentelemetry-api", version.ref = "opentelemetry" }
io-opentelemetry-opentelemetry-context = { group = "io.opentelemetry", name = "opentelemetry-context", version.ref = "opentelemetry" }
jakarta-annotation-jakarta-annotation-api = { group = "jakarta.annotation", name = "jakarta.annotation-api", version = "2.1.1" }
javax-xml-stream-stax-api = { group = "javax.xml.stream", name = "stax-api", version = "1.0-2" }
org-junit-jupiter-junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version = "6.0.1" }
org-junit-platform-junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version = "6.0.1" }
org-mockito-mockito-core = { group = "org.mockito", name = "mockito-core", version = "5.20.0" }

[plugins]
com-diffplug-spotless = { id = "com.diffplug.spotless", version = "8.1.0" }
com-github-spotbugs = { id = "com.github.spotbugs", version = "6.4.7" }
org-sonarqube = { id = "org.sonarqube", version = "7.1.0.6387" }
